In [1]:
import lasio

In [2]:
las = lasio.read('/home/dell/GSDMA2019/lasio/standards/examples/2.0/sample_2.0.las')

In [3]:
las.header

{'Curves': [CurveItem(mnemonic=DEPT, unit=M, value=, descr=1  DEPTH, original_mnemonic=DEPT, data.shape=(3,)),
  CurveItem(mnemonic=DT, unit=US/M, value=60 520 32 00, descr=2  SONIC TRANSIT TIME, original_mnemonic=DT, data.shape=(3,)),
  CurveItem(mnemonic=RHOB, unit=K/M3, value=45 350 01 00, descr=3  BULK DENSITY, original_mnemonic=RHOB, data.shape=(3,)),
  CurveItem(mnemonic=NPHI, unit=V/V, value=42 890 00 00, descr=4  NEUTRON POROSITY, original_mnemonic=NPHI, data.shape=(3,)),
  CurveItem(mnemonic=SFLU, unit=OHMM, value=07 220 04 00, descr=5  SHALLOW RESISTIVITY, original_mnemonic=SFLU, data.shape=(3,)),
  CurveItem(mnemonic=SFLA, unit=OHMM, value=07 222 01 00, descr=6  SHALLOW RESISTIVITY, original_mnemonic=SFLA, data.shape=(3,)),
  CurveItem(mnemonic=ILM, unit=OHMM, value=07 120 44 00, descr=7  MEDIUM RESISTIVITY, original_mnemonic=ILM, data.shape=(3,)),
  CurveItem(mnemonic=ILD, unit=OHMM, value=07 120 46 00, descr=8  DEEP RESISTIVITY, original_mnemonic=ILD, data.shape=(3,))],
 '

In [4]:
type (las.data)

numpy.ndarray

In [5]:
las.data.shape

(3, 8)

In [7]:
for curve in las.curves:
    print(curve.mnemonic)
    print(curve.unit)
    print(curve.data)
    print("\n")

DEPT
M
[1670.    1669.875 1669.75 ]


DT
US/M
[123.45 123.45 123.45]


RHOB
K/M3
[2550. 2550. 2550.]


NPHI
V/V
[0.45 0.45 0.45]


SFLU
OHMM
[123.45 123.45 123.45]


SFLA
OHMM
[123.45 123.45 123.45]


ILM
OHMM
[110.2 110.2 110.2]


ILD
OHMM
[105.6 105.6 105.6]


